name: Github Actions Workflow

on:    
    pull_request:
        types: [opened,synchronize]
        branches: [main,master]

jobs:
    job1:
        name: Job 1
        runs-on: ubuntu-latest
        outputs:
          pr-description: ${{ steps.setvars.outputs.var1 }}
          current-branch: ${{ steps.setvars.outputs.var3 }}

        steps:
            - name: Step 1
              shell: bash
              id: setvars
              run: | 
                echo "var1=${{ github.event.pull_request.body }}" >> $GITHUB_OUTPUT
                echo "var3=${{ github.event.pull_request.head.ref }}" >> $GITHUB_OUTPUT
                



    job2:
        name: Job 2
        runs-on: ubuntu-latest
        needs: job1

        steps:
            - name: Step 1
              shell: pwsh
              run: |  
                $rawDescription = "${{needs.job1.outputs.pr-description}}"
                $fixedJson = $rawDescription -replace '(\w+):', '"$1":' -replace ':([a-zA-Z0-9_]+)([,\}])', ':"$1"$2' 
                $body = @{
                    Description = $fixedJson
                    Branch = "${{needs.job1.outputs.current-branch}}"
                    BaseUrl = "https://localhost:7005"
                } | ConvertTo-Json -Depth 5
                echo "$fixedJson"
                echo "$escapedDescription"
                echo "$fixedJson"


