name: Github Actions Workflow

on:    
    pull_request:
        types: [opened,synchronize]
        branches: [main,master]

jobs:
    job1:
        name: Job 1
        runs-on: ubuntu-latest
        outputs:
          pr-description: ${{ steps.setvars.outputs.var1 }}
          target-branch: ${{ steps.setvars.outputs.var2 }}
          current-branch: ${{ steps.setvars.outputs.var3 }}

        steps:
            - name: Step 1
              shell: bash
              id: setvars
              run: | 
                echo "var1=${{ github.event.pull_request.body }}" >> $GITHUB_OUTPUT
                echo "var2=${{ github.event.pull_request.base.ref }}" >> $GITHUB_OUTPUT
                echo "var3=${{ github.event.pull_request.head.ref }}" >> $GITHUB_OUTPUT
                



    job2:
        name: Job 2
        runs-on: ubuntu-latest
        needs: job1

        steps:
            - name: Step 1
              shell: bash
              run: | 
                echo "PR Description from Job 1: "
                Description "${{needs.job1.outputs.pr-description}}
                Target branch from Job 1: ${{needs.job1.outputs.target-branch}}
                Current Branch from Job 1: ${{needs.job1.outputs.current-branch}}"

