name: Github Actions Workflow

on:    
    pull_request:
        types: [opened,synchronize]
        branches: [main,master]

jobs:
    job1:
        name: Job 1
        runs-on: ubuntu-latest

        steps:
            - name: Step 1
              shell: bash
              run: | 
                echo "PR Description: "
                echo "${{github.event.pull_request.body}}
                Target branch: ${{github.event.pull_request.base.ref}}
                Current Branch: ${{github.event.pull_request.head.ref}}"

